// controllers/strategyController.ts
import { Response, Request } from "express";
import {
  changeStrategyStatus,
  createStrategy,
  deleteStrategy,
  getStrategyById,
  getUserStrategies,
  updateStrategy,
} from "../services/strategyService";
import {
  sendBadRequest,
  sendSuccess,
  sendServerError,
} from "../utils/response";
import {
  subscribeStrategyToMarketData,
  unsubscribeStrategyFromMarketData,
} from "../sockets/marketDataRouter";
import { strategyRuntimeRegistry } from "../services/strategies/strategyRuntimeRegistry";
import { CryptoExchange, StocksExchange } from "@prisma/client";
import { registerStrategy, unregisterStrategy } from "../strategies/dispatcher";
import { scheduleStrategy } from "../utils/scheduleStrategy";
import { deleteSchedule } from "../utils/awsScheduler";
import { calculateBollingerBands } from "../utils/strategies/gridCalculations";
import { MarketDataManager } from "../sockets/crypto/marketData/marketDataManager";
import { fetchBinanceHistoricalKlines } from "../services/crypto/exchange/binanceService";
import {
  fetchHistoricalPrices,
  validateInterval,
  normalizeInterval
} from "../utils/strategies/historicalDataFetcher";

/**
 * Calculate Smart Grid limits based on Bollinger Bands
 */
/**
 * Calculate Smart Grid limits based on Bollinger Bands with historical data
 */
/**
 * ✅ UPDATED: Calculate Smart Grid limits with data set integration
 */
export const calculateSmartGridLimits = async (req: Request, res: Response) => {
  try {
    const {
      exchange,
      segment,
      symbol,
      dataSetDays = 30,
      investment,
      minimumInvestment,
    } = req.body;

    // Validate input
    if (!exchange || !segment || !symbol) {
      return sendBadRequest(
        res,
        "exchange, segment, and symbol are required"
      );
    }

    // Validate segment
    if (!["SPOT", "FUTURES"].includes(segment)) {
      return sendBadRequest(res, "segment must be SPOT or FUTURES");
    }

    // Validate exchange
    const supportedExchanges = ["BINANCE", "KUCOIN", "COINDCX"];
    if (!supportedExchanges.includes(exchange.toUpperCase())) {
      return sendBadRequest(
        res,
        `Exchange ${exchange} not supported. Supported: ${supportedExchanges.join(", ")}`
      );
    }

    // Validate dataSetDays
    const validDataSets = [3, 7, 30, 180, 365];
    if (!validDataSets.includes(dataSetDays)) {
      return sendBadRequest(
        res,
        `dataSetDays must be one of: ${validDataSets.join(", ")}`
      );
    }

    // ✅ Validate investment only if provided
    if (investment !== undefined && investment <= 0) {
      return sendBadRequest(res, "investment must be positive");
    }

    // ✅ Validate minimumInvestment only if provided
    if (minimumInvestment !== undefined) {
      if (minimumInvestment <= 0) {
        return sendBadRequest(res, "minimumInvestment must be positive");
      }

      if (minimumInvestment > investment) {
        return sendBadRequest(res, "minimumInvestment cannot exceed investment");
      }
    }

    console.log("[CALCULATE_SMART_GRID_LIMITS] Request", {
      exchange,
      segment,
      symbol,
      dataSetDays,
      investment,
      minimumInvestment,
    });

    // ✅ Generate all parameters automatically
    const { generateSmartGridParams } = await import(
      "../services/strategies/indicatorCalculator.js"
    );

    const result = await generateSmartGridParams({
      exchange,
      symbol,
      dataSetDays,
      segment: segment as "SPOT" | "FUTURES",
      investment,
      minimumInvestment,
      // No user overrides - let it calculate everything
    });

    console.log("[CALCULATE_SMART_GRID_LIMITS] Success", {
      exchange,
      segment,
      symbol,
      result,
    });

    return sendSuccess(res, "Smart Grid parameters calculated successfully", {
      exchange: result.exchange,
      symbol: result.symbol,
      segment: result.segment,

      // ✅ Auto-calculated parameters
      upperLimit: result.upperLimit,
      lowerLimit: result.lowerLimit,
      levels: result.levels,
      profitPercentage: result.profitPercentage,
      minimumInvestment: result.minimumInvestment,

      // ✅ Investment breakdown
      investment: result.investment,
      perLevelInvestment: result.perLevelInvestment,

      // ✅ Validation feedback
      validation: result.validation,

      // ✅ Recommendations
      recommendations: {
        minimumInvestmentRequired: result.validation.minimumInvestmentRequired,
        maxAffordableLevels: result.validation.maxAffordableLevels,
      },

      // ✅ Indicators (for transparency)
      indicators: result.indicators,

      metadata: {
        dataSetDays: result.dataSetDays,
        calculationMethod: "Bollinger Bands + ATR + Volatility Analysis",
        autoGenerated: true,
      },

      calculatedAt: new Date().toISOString(),
    });
  } catch (error: any) {
    console.error("[CALCULATE_SMART_GRID_LIMITS] Error", {
      error: error.message,
      stack: error.stack,
    });
    return sendServerError(res, error.message);
  }
};
/**
 * Calculate Smart Grid limits with historical data (enhanced version)
 */
export const calculateSmartGridLimitsEnhanced = async (
  req: Request,
  res: Response
) => {
  try {
    const {
      exchange,
      segment,
      symbol,
      period = 20,
      stdDev = 2,
      dataSetDays = 30,
    } = req.body;

    // Validate input
    if (!exchange || !segment || !symbol) {
      return sendBadRequest(res, "exchange, segment, and symbol are required");
    }

    console.log("[CALCULATE_SMART_GRID_LIMITS_ENHANCED] Request", {
      exchange,
      segment,
      symbol,
      period,
      stdDev,
      dataSetDays,
    });

    // TODO: Fetch historical candles from Binance API
    // For now, return error message
    return sendServerError(
      res,
      "Historical data fetching not implemented yet. Use /calculate-smart-grid-limits for basic calculation."
    );

    /*
    // Future implementation:
    const historicalData = await fetchHistoricalCandles(
      exchange,
      segment,
      symbol,
      dataSetDays
    );
    
    const closePrices = historicalData.map(candle => candle.close);
    const bands = calculateBollingerBands(closePrices, period, stdDev);
    
    return sendSuccess(res, "Smart Grid limits calculated", {
      upperLimit: bands.upper,
      lowerLimit: bands.lower,
      middlePrice: bands.middle,
      currentPrice: closePrices[closePrices.length - 1],
      dataPoints: closePrices.length,
      period,
      stdDev,
      calculatedAt: new Date().toISOString(),
    });
    */
  } catch (error: any) {
    console.error("[CALCULATE_SMART_GRID_LIMITS_ENHANCED] Error", {
      error: error.message,
      stack: error.stack,
    });
    return sendServerError(res, error.message);
  }
};
export const createStrategyController = async (req: any, res: Response) => {
  const userId = req.user.userId;

  const {
    name, // Renamed from 'name' to 'strategyName'
    strategyType,
    assetType,
    exchange,
    segment,
    symbol,
    investmentPerRun,
    investmentCap,
    frequency,
    takeProfitPct,
    stopLossPct,
    priceStart,
    priceStop,
    time,
    hourInterval,
    daysOfWeek,
    datesOfMonth,
    executionMode,
    // Human Grid
    lowerLimit,
    upperLimit,
    entryInterval, // Kept for Human Grid
    bookProfitBy, // Kept for Human Grid
    leverage,
    direction,
    // Smart Grid - NEW FIELDS
    type, // ✅ NEUTRAL | LONG | SHORT
    levels,
    profitPercentage, // ✅ Profit per level (%)
    dataSetDays,
    gridMode,
    recalculationInterval,
    investment: userInvestment, // ✅ Total investment (renamed to avoid conflict with auto-calculated 'investment')
    minimumInvestment: userMinInvestment, // ✅ Minimum investment per order (renamed)
    perGridAmount, // ✅ NEW: Smart Grid editable parameters
    // UTC - NEW FIELDS
    timeFrame,
    upperLimit: utcUpperLimit,
    lowerLimit: utcLowerLimit,
    // INDY_TREND - NEW FIELDS
    mode,
    priceTriggerStart,
    priceTriggerStop,
    stopLossByPercent,
    riskRewardRatio,
    supertrendFactor,
    supertrendAtrLength,
    rsiLength,
    rsiUpperBand,
    rsiLowerBand,
    adxSmoothing,
    adxDiLength,
    adxThreshold,
    partialExit,
    trailingStop,
    // LESI - NEW FIELDS
    lcEnabled,
    lcSource,
    emaEnabled,
    emaLength,
    emaSource,
    laRSIEnabled,
    laRSIAlpha,
    laRSISource,
  } = req.body;


  const baseRequiredFields = {
    name,
    strategyType,
    exchange,
    segment,
    symbol,
    executionMode,
  };

  if (strategyType === "HUMAN_GRID") {
    const gridRequiredFields = {
      ...baseRequiredFields,
      lowerLimit,
      upperLimit,
      entryInterval,
      bookProfitBy,
      investmentPerRun,
      investmentCap,
    };

    const missingFields = Object.entries(gridRequiredFields)
      .filter(([_, value]) => value === undefined || value === null || value === "")
      .map(([key]) => key);

    if (missingFields.length > 0) {
      return sendBadRequest(
        res,
        `Missing required fields: ${missingFields.join(", ")}`
      );
    }

    if (segment === "FUTURES") {
      if (!leverage || !direction) {
        return sendBadRequest(
          res,
          "leverage and direction are required for FUTURES segment"
        );
      }
    }
  } else if (strategyType === "SMART_GRID") {
    // ✅ UPDATED: New required fields    // ✅ Smart Grid required fields (some are now optional for auto-calculation)
    const smartGridRequiredFields = {
      name, // Renamed from 'name'
      strategyType,
      exchange,
      segment,
      symbol,
      executionMode,
      type, // ✅ NEUTRAL | LONG | SHORT
      dataSetDays,
      // ✅ NOTE: levels, profitPercentage, investment, minimumInvestment, perGridAmount are now optional
      // The system will auto-calculate missing values based on what's provided
    };

    const missingFields = Object.entries(smartGridRequiredFields)
      .filter(([key, value]) => {
        // Allow certain fields to be undefined/null/empty if they are optional
        const optionalFields = [
          'levels',
          'profitPercentage',
          'investment',
          'minimumInvestment',
          'perGridAmount',
        ];
        if (optionalFields.includes(key)) {
          return false; // Don't mark as missing if it's an optional field
        }
        return value === undefined || value === null || value === "";
      })
      .map(([key]) => key);

    if (missingFields.length > 0) {
      return sendBadRequest(
        res,
        `Missing required fields: ${missingFields.join(", ")}`
      );
    }

    // ✅ Validate type
    if (!["NEUTRAL", "LONG", "SHORT"].includes(type)) {
      return sendBadRequest(
        res,
        "type must be one of: NEUTRAL, LONG, SHORT"
      );
    }

    // ✅ Validate dataSetDays
    const validDataSets = [3, 7, 30, 180, 365];
    if (!validDataSets.includes(dataSetDays)) {
      return sendBadRequest(
        res,
        `dataSetDays must be one of: ${validDataSets.join(', ')}`
      );
    }

    // ✅ Validate levels
    if (levels < 2 || levels > 50) {
      return sendBadRequest(
        res,
        "levels must be between 2 and 50"
      );
    }

    // ✅ Validate profit percentage
    if (profitPercentage <= 0 || profitPercentage > 100) {
      return sendBadRequest(
        res,
        "profitPercentage must be between 0 and 100"
      );
    }

    // ✅ Validate investment amounts (only if provided)
    if (userInvestment !== undefined && userInvestment <= 0) {
      return sendBadRequest(res, "investment must be positive");
    }

    if (userMinInvestment !== undefined && userMinInvestment <= 0) {
      return sendBadRequest(res, "minimumInvestment must be positive");
    }

    if (userInvestment && userMinInvestment && userMinInvestment > userInvestment) {
      return sendBadRequest(
        res,
        "minimumInvestment cannot exceed total investment"
      );
    }

    // ✅ Validate perGridAmount if provided
    if (perGridAmount !== undefined && perGridAmount <= 0) {
      return sendBadRequest(res, "perGridAmount must be positive");
    }

    // ✅ Validate consistency if multiple parameters provided
    if (perGridAmount && levels && userInvestment) {
      const calculatedInvestment = perGridAmount * levels;
      if (Math.abs(calculatedInvestment - userInvestment) > 0.01) {
        return sendBadRequest(
          res,
          `Parameter inconsistency: perGridAmount (${perGridAmount}) × levels (${levels}) = ${calculatedInvestment}, but investment is ${userInvestment}`
        );
      }
    }

    if (segment === "FUTURES") {
      if (!leverage || !direction) {
        return sendBadRequest(
          res,
          "leverage and direction are required for FUTURES segment"
        );
      }
    }
  } else if (strategyType === "UTC") {
    // ✅ UTC Strategy Validation
    const utcRequiredFields = {
      ...baseRequiredFields,
      investmentPerRun,
      investmentCap,
      timeFrame,
    };

    const missingUtcFields = Object.entries(utcRequiredFields)
      .filter(([_, value]) => value === undefined || value === null || value === "")
      .map(([key]) => key);

    if (missingUtcFields.length > 0) {
      return sendBadRequest(
        res,
        `Missing required fields for UTC strategy: ${missingUtcFields.join(", ")}`
      );
    }

    // ✅ Validate leverage for FUTURES
    if (segment === "FUTURES" && !leverage) {
      return sendBadRequest(res, "leverage is required for FUTURES segment");
    }
  } else if (strategyType === "INDY_TREND") {
    // ✅ INDY TREND Strategy Validation
    const indyTrendRequiredFields = {
      ...baseRequiredFields,
      investment: userInvestment,
      timeFrame,
    };

    const missingIndyFields = Object.entries(indyTrendRequiredFields)
      .filter(([_, value]) => value === undefined || value === null || value === "")
      .map(([key]) => key);

    if (missingIndyFields.length > 0) {
      return sendBadRequest(
        res,
        `Missing required fields for INDY_TREND strategy: ${missingIndyFields.join(", ")}`
      );
    }
  } else if (strategyType === "LESI") {
    // ✅ LESI Strategy Validation
    const lesiRequiredFields = {
      ...baseRequiredFields,
      investment: userInvestment,
      timeFrame,
    };

    const missingLesiFields = Object.entries(lesiRequiredFields)
      .filter(([_, value]) => value === undefined || value === null || value === "")
      .map(([key]) => key);

    if (missingLesiFields.length > 0) {
      return sendBadRequest(
        res,
        `Missing required fields for LESI strategy: ${missingLesiFields.join(", ")}`
      );
    }

    // Validate leverage for FUTURES
    if (segment === "FUTURES" && assetType === "CRYPTO") {
      if (!leverage || leverage < 1 || leverage > 20) {
        return sendBadRequest(
          res,
          "leverage must be between 1x and 20x for Crypto Futures"
        );
      }
    }
  } else {
    // Growth DCA validation
    const requiredFields = {
      ...baseRequiredFields,
      frequency,
      investmentPerRun,
      investmentCap,
    };

    const missingFields = Object.entries(requiredFields)
      .filter(([_, value]) => value === undefined || value === null || value === "")
      .map(([key]) => key);

    if (missingFields.length > 0) {
      return sendBadRequest(
        res,
        `Missing required fields: ${missingFields.join(", ")}`
      );
    }
  }

  try {
    const strategy = await createStrategy({
      userId,
      name,
      strategyType,
      assetType,
      exchange,
      segment,
      symbol,
      investmentPerRun,
      investmentCap,
      frequency,
      takeProfitPct,
      stopLossPct,
      priceStart,
      priceStop,
      time,
      hourInterval,
      daysOfWeek,
      datesOfMonth,
      executionMode,
      // Human Grid
      lowerLimit,
      upperLimit,
      entryInterval,
      bookProfitBy,
      leverage,
      direction,
      // Smart Grid
      type,
      levels,
      profitPercentage,
      dataSetDays,
      gridMode,
      recalculationInterval,
      investment: userInvestment, // ✅ Pass renamed variable
      minimumInvestment: userMinInvestment, // ✅ Pass renamed variable
      perGridAmount, // ✅ NEW: Pass perGridAmount
      // UTC
      timeFrame,
      utcUpperLimit,
      utcLowerLimit,
      // INDY_TREND
      mode,
      priceTriggerStart,
      priceTriggerStop,
      stopLossByPercent,
      riskRewardRatio,
      supertrendFactor,
      supertrendAtrLength,
      rsiLength,
      rsiUpperBand,
      rsiLowerBand,
      adxSmoothing,
      adxDiLength,
      adxThreshold,
      partialExit,
      trailingStop,
      // LESI
      lcEnabled,
      lcSource,
      emaEnabled,
      emaLength,
      emaSource,
      laRSIEnabled,
      laRSIAlpha,
      laRSISource,
    });

    if (
      strategy.executionMode === "LIVE" ||
      strategy.executionMode === "PUBLISHED"
    ) {
      await registerStrategy(strategy.id);

      // Only schedule TIME-BASED strategies
      if (strategy.type !== "HUMAN_GRID" && strategy.type !== "SMART_GRID" && strategy.nextRunAt) {
        const lambdaArn = process.env.RUN_STRATEGY_LAMBDA_ARN!;
        await scheduleStrategy({ strategy, lambdaArn });
      } else {
        console.log("[STRATEGY_SIGNAL_BASED] No AWS schedule needed", {
          strategyId: strategy.id,
          type: strategy.type,
        });
      }
    }

    if (strategy.executionMode === "BACKTEST") {
      console.log("[BACKTEST] Enqueue job for strategy:", strategy.id);
    }

    return sendSuccess(res, "Strategy created", strategy);
  } catch (error: any) {
    console.error("[CREATE_STRATEGY_ERROR]", error);
    return sendServerError(res, error.message);
  }
};

export const getStrategyByIdController = async (req: any, res: Response) => {
  try {
    const strategy = await getStrategyById(req.params.strategyId);
    return sendSuccess(res, "Strategy fetched", strategy);
  } catch (error: any) {
    return sendServerError(res, error.message);
  }
};

export const getUserStrategiesController = async (req: any, res: Response) => {
  const userId = req.user.userId;

  try {
    const strategies = await getUserStrategies(userId);
    return sendSuccess(res, "User strategies fetched successfully", strategies);
  } catch (error: any) {
    console.error("[STRATEGY_CONTROLLER] Failed to fetch strategies", error);
    return sendServerError(res, error.message || "Failed to fetch strategies");
  }
};

export const updateStrategyController = async (req: any, res: Response) => {
  const userId = req.user.userId;
  const { strategyId } = req.params;

  try {
    const oldStrategy = await getStrategyById(strategyId);

    const updated = await updateStrategy(strategyId, userId, req.body);

    // 1. Unsubscribe old
    await unsubscribeStrategyFromMarketData({
      assetType: oldStrategy.assetType as "CRYPTO" | "STOCK",
      exchange: oldStrategy.exchange as any,
      segment: oldStrategy.segment,
      symbol: oldStrategy.symbol,
      strategyId: oldStrategy.id,
      userId: oldStrategy.userId,
    });

    // 2. Reset runtime
    await unregisterStrategy(strategyId);

    // 3. Resubscribe new
    if (updated.status === "ACTIVE") {
      await registerStrategy(strategyId);

      const lambdaArn = process.env.RUN_STRATEGY_LAMBDA_ARN!;
      await scheduleStrategy({ strategy: updated, lambdaArn });
    }
    return sendSuccess(res, "Strategy updated", updated);
  } catch (error: any) {
    console.error("[STRATEGY_UPDATE]", error);
    return sendServerError(res, error.message);
  }
};

export const deleteStrategyController = async (req: any, res: Response) => {
  const userId = req.user.userId;
  const { strategyId } = req.params;

  try {
    const strategy = await getStrategyById(strategyId);

    await unsubscribeStrategyFromMarketData({
      assetType: strategy.assetType as "CRYPTO" | "STOCK",
      exchange: strategy.exchange as any,
      segment: strategy.segment,
      symbol: strategy.symbol,
      strategyId: strategy.id,
      userId: strategy.userId,
    });

    await unregisterStrategy(strategyId);

    await deleteStrategy(strategyId, userId);

    const scheduleName = `strategy-${strategy.id}`;
    await deleteSchedule(scheduleName);

    return sendSuccess(res, "Strategy deleted");
  } catch (error: any) {
    console.error("[STRATEGY_DELETE]", error);
    return sendServerError(res, error.message);
  }
};

export const updateStrategyStatusController = async (
  req: any,
  res: Response,
) => {
  const userId = req.user.userId;
  const { strategyId } = req.params;
  const { status } = req.body;

  if (!["ACTIVE", "PAUSED", "STOPPED"].includes(status)) {
    return sendBadRequest(res, "Invalid status");
  }

  try {
    const strategy = await getStrategyById(strategyId);

    // 1️⃣ Leaving ACTIVE → teardown
    if (strategy.status === "ACTIVE" && status !== "ACTIVE") {
      await unregisterStrategy(strategyId);
      await deleteSchedule(`strategy-${strategyId}`);
    }

    // 2️⃣ Persist status
    const updated = await changeStrategyStatus(strategyId, userId, status);

    // 3️⃣ Entering ACTIVE → setup
    if (updated.status === "ACTIVE") {
      await registerStrategy(strategyId);

      const lambdaArn = process.env.RUN_STRATEGY_LAMBDA_ARN!;
      await scheduleStrategy({ strategy: updated, lambdaArn });
    }

    return sendSuccess(res, "Strategy status updated", updated);
  } catch (error: any) {
    return sendServerError(res, error.message);
  }
};
